spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  application:
    name: lab-3
  h2:
    console:
      enabled: true
      path: /h2-console
  docker:
    compose:
      file: labs/lab-3/compose.yaml
server:
  port: 8888
